### ISSUE TITLE
KDTree nearest neighbor not returning nearest within subset

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/NetworkBuild#21]
Encountered several instances where the KDTree is not returning the nearest neighbor *within* the subset.  This results in an incomplete Minimum Spanning Forest (as certain edges are skipped).

**Comment by chrisnatali** [comment]
On closer inspection, this is not a problem with the KDTree, it's #22.

**Comment by blogle** [comment]
If my kdtree didn't work I was going to have to doubt everything else in my life.

**Comment by chrisnatali** [comment]
Considering that you actually handle the special case of retaining fake node np.Inf mv values in UnionFind.union separate from their parents mv values [here](https://github.com/SEL-Columbia/NetworkBuild/blob/master/networkbuild/utils.py#L126), I might still doubt everything in your life @blogle :)

**Comment by blogle** [comment]
Fake nodes will hijack the network any chance they get. Fake nodes are bad nodes, I had to ensure they weren't fraternizing with the rest of the sets mv.
